source= ~/.config/hypr/defaultapps.conf
source= ~/.config/hypr/autostart.conf
source= ~/.config/hypr/cursor.conf
source= ~/.config/hypr/monitors.conf
source= ~/.config/hypr/looknfeel.config
source= ~/.config/hypr/permissions.conf
source= ~/.config/hypr/keybinds.conf
source= ~/.config/hypr/wnw.conf
source= ~/.config/hypr/misc.conf
