#waybar

#layerrule = blur, waybar
#layerrule = ignorezero, waybar
#layerrule = ignorealpha 0.5, waybar

#windowrulev2 = opacity 0.8, class:^(code)$
#windowrulev2 = opacity 0.8 0.8, class:^(code-url-handler)$

#brightness
# ~/.config/hypr/hyprland.conf
bind = , XF86MonBrightnessUp, exec, brightnessctl set +5%
bind = , XF86MonBrightnessDown, exec, brightnessctl set 5%-

#dock
#exec-once = sleep 10 && nwg-dock-hyprland -x -p "left"  -i 24 -mt 10 -mb 10 -ml 5 -f
bind = ALT SHIFT , H , exec, nwg-dock-hyprland -x -p "left"  -i 24 -mt 10 -mb 10 -ml 5 -f
#layerrule = blur ,gtk-layer-shell 

device {
	name = sony-interactive-entertainment-dualsense-wireless-controller-touchpad
	enabled = false
}

misc:initial_workspace_tracking = 1
